
#define EVMJIT_VERSION "0.9.0.2"
#define EVMJIT_VERSION_MAJOR 0
#define EVMJIT_VERSION_MINOR 9
#define EVMJIT_VERSION_PATCH 0

#define LLVM_VERSION ""
#define LLVM_ASSERTIONS ""
#define LLVM_DEBUG 0
